### PR TITLE
incorporate Lyumjev insulin

### PR DESCRIPTION
**Pull request by mountrcg**
I added a Lyumjev preset with DIA 5.5h (330min) and peak at 45 min. I did not see where it gets tied into the ultraRapid/ultra-rapid insulin curve, but neither is Fiasp apart from that is an ExponentialInsulinModelPreset.

### CODE REVIEW

**Comment by mountrcg** [comment]
The link between the chosen Insulin type and the OpenAPS insulin curve seems to be missing in general. Or more precisely the Insulin information ActionDuration (DIA), PeakTime and Model only seems to tie into Loops ExponentialInsulinModel and not into OpenAPS:
One could link FIASP and Lyumjev to ultra-rapid and the rest to rapid-acting insulin curves of OpenAPS.
Same seems to the case for the ActionDuration (DIA) setting, dia = settings.insulinActionCurve, which is preset to 5 instead the parameters of chosen insulin.

**Comment by ivalkou** [comment]
Yes, it would be logical to associate insulin type with insulin curve parameter. For Lumjev, it may be necessary to change insulin peak time.

**Comment by mountrcg** [comment]
I have set it to 45min in comparison to 55min for FIASP, which is in accordance to what people do on AAPS.

**Comment by mountrcg** [comment]
I guess presets would be:
Apidra, Humalog & Novolog ->rapidActing(peak:75min, DIA 360min)
Fiasp -> ultraRapid(peak:55min, DIA 360min)
Lyumjev -> "hyper"Rapid(peak:45, DIA 330min)

I think you only used from LoopKit:
InsulinType.swift , HKQuantitySample+InsulinKit.swift but not ExponentialInsulinModelPreset.swift

**Review by DobbyWanKenoby — APPROVED** [review]
'APPROVE' performed by Xcode.

**Review by DobbyWanKenoby — APPROVED** [review]
'APPROVE' performed by Xcode.

**Pull request merged**
